# GOAL: Retrieving the results (CSV files) generated by Airflow and uploading them to GitHub.   
import subprocess # It runs shell commands from Python, like git clone, git add, etc.
import os
import shutil # file copy and delete 

def git_push_data():
    try:
        git_email = os.getenv("GIT_EMAIL")
        git_user = os.getenv("GIT_USER_NAME")
        git_token = os.getenv("GITHUB_TOKEN")
        git_repo = os.getenv("GITHUB_REPO") 

        # 1. Let's create a temporary folder in the container's memory. This is where I will clone the GitHub repository and prepare the files for pushing. I will use /tmp/air_sync as my working directory for this process.
        temp_dir = "/tmp/air_sync"
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir) # if it exists, delete it, otherwise it will give an error during cloning
        
        # 2. CLONING my repo to the temp_directory.
        remote_url = f"https://{git_token}@{git_repo}"
        print("Fetching repo from GitHub...")
        subprocess.run(["git", "clone", "--depth", "1", remote_url, temp_dir], check=True) # clone to /tmp/air_sync folder

        #3. Find the CSV files generated by Airflow (From the address inside the container, not the one I created with COPY)
        source_csv_path = "/opt/airflow/dashboard/data/" # The path where Airflow writes the CSV files inside the container. This is the source path for the CSV files that I want to push to GitHub.
        target_csv_path = os.path.join(temp_dir, "dashboard/data/") # String birleştirip path oluşturuyor. CSV’lerin taşınacağı yer
        
        os.makedirs(target_csv_path, exist_ok=True)
        
        print("Moving newly generated data to sync folder...")
        for file in os.listdir(source_csv_path):
            if file.endswith(".csv"):
                shutil.copy(os.path.join(source_csv_path, file), target_csv_path)

        # 4. Git Process: Add, Commit, Push
        os.chdir(temp_dir) # Terminali bu klasöre götür (git komutları burada çalışacak) Yani çalışma dizinini değiştirdim çünkü Git komutları hangi klasörde çalıştığına bağlıdır.
        subprocess.run(["git", "config", "user.email", git_email], check=True)
        subprocess.run(["git", "config", "user.name", git_user], check=True)
        print("Forcing add dashboard/data CSVs...")
        subprocess.run(["git", "add", "-f", "dashboard/data/*.csv"], check=True)
        # Add remaining changes (if any)
        subprocess.run(["git", "add", "."], check=True)
        # Is there any change to commit?
        status = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True).stdout
        if status:
            print("Updates found! Pushing to GitHub...")
            subprocess.run(["git", "commit", "-m", "Auto-update dashboard data [Airflow]"], check=True)
            subprocess.run(["git", "push", "origin", "main"], check=True)
            print("--- PUSH SUCCESSFUL ---")
        else:
            print("No new data to push.")

    except Exception as e:
        print(f"FAILED: {e}")
        raise e